### ISSUE TITLE
Implement LDAPUR & STLUR for better dataflow

### ISSUE THREAD

**Issue by verylazyguy** [Vector35/arch-arm64#101]
Load-Acquire RCpc Register (unscaled) - LDAPUR[S][BH]
Store-Release Register (unscaled) - STLUR[BH]

**Comment by lwerdna** [comment]
@verylazyguy Do you have a binary exhibiting broken dataflow with these instructions?

**Comment by brinlyau** [comment]
Not exactly a minimised binary, but the iOS kernelcache has a few of these :)

**Comment by verylazyguy** [comment]
Unfortunately I can't find a minimized binary, just an iOS kernelcache. The "broken" dataflow is simply that it's unimplemented so dataflow doesn't know data is being loaded into a register
![Screen Shot 2022-07-09 at 11 39 02 AM](https://user-images.githubusercontent.com/4371276/178112684-7e628bbd-d48e-422d-a391-eb79c0d08e1d.png)

**Comment by lwerdna** [comment]
Keystone won't assemble it, but with the specs we can construct some samples:

```
D9418108: ldapur	x8, [x8, #0x18]
D9018108: stlur	x8, [x8, #0x18]
```

![sample](https://user-images.githubusercontent.com/474191/189230984-e3b0f34c-cd35-4bb0-9eea-78e4f9d26b68.png)

[sample.zip](https://github.com/Vector35/arch-arm64/files/9530765/sample.zip)

**Comment by lwerdna** [comment]
I'm going to treat these like we currently treat load-acquire instructions and ignore the processor consistency attribute.

Notes dump:

```
character meanings in the mnemonics:

lda: load-acquire
stl: store-release
  p: 'processor consistent' from "Release Consistent processor consistent (RCpc)"
  u: unscaled
  r: register
  s: signed
  b: byte
  h: halfword
  w: word

ldapurb  unscaled register        byte     LDAPURB  <Wt>, [<Xn|SP>{, #<simm>}]
ldapursb unscaled register signed byte     LDAPURSB <Wt>, [<Xn|SP>{, #<simm>}]
                                           LDAPURSB <Xt>, [<Xn|SP>{, #<simm>}]
ldapurh  unscaled register        halfword LDAPURH  <Wt>, [<Xn|SP>{, #<simm>}]
ldapursh unscaled register signed halfword LDAPURH  <Wt>, [<Xn|SP>{, #<simm>}]
ldapursw unscaled register signed word     LDAPURSW <Xt>, [<Xn|SP>{, #<simm>}]

ldapr             register                 LDAPR    <Wt>, [<Xn|SP> {,#0}]
                                           LDAPR    <Xt>, [<Xn|SP> {,#0}]
ldaprb            register        byte     LDAPRB   <Wt>, [<Xn|SP> {,#0}]
ldaprh            register        halfword LDAPRH   <Wt>, [<Xn|SP> {,#0}]

stlur    unscaled register                 STLUR    <Wt>, [<Xn|SP>{, #<simm>}]
                                           STLUR    <Xt>, [<Xn|SP>{, #<simm>}]
stlurb   unscaled register        byte     STLURB   <Xt>, [<Xn|SP>{, #<simm>}]
stlurh   unscaled register        halfword STLURH   <Wt>, [<Xn|SP>{, #<simm>}]

https://en.wikipedia.org/wiki/Release_consistency
https://en.wikipedia.org/wiki/Processor_consistency
https://en.wikipedia.org/wiki/Consistency_model
```
