### ISSUE TITLE
Lifting pointer auth instructions

### ISSUE THREAD

**Issue by brinlyau** [Vector35/arch-arm64#22]
Maybe some discussion on how we want to do this, but I've listed some examples here on instructions to lift from this example [dyld arm64e binary](https://drive.google.com/file/d/1ChbTlzoOSTJ52q5xJ6bfr-4shXxVQq8Z/view?usp=sharing) , so the other issue is just more standard arm64 stuff 

>
>  unlifted instructions in bndb
>     1432         pacibsp [0x107c, 0x12b0, 0x1340, 0x1374, 0x13a8, 0x140c, 0x1588, 0x15f8, ...]
>      304           pacia [0x1104, 0x1118, 0x1168, 0x11d8, 0x6a90, 0x840c, 0x848c, 0x85a0, ...]
>      236           pacda [0x1148, 0x11b8, 0x6a70, 0x83e4, 0x8474, 0x858c, 0x86a0, 0x87b4, ...]
>      176         autibsp [0x2c4c, 0x4dc8, 0x6548, 0x65e4, 0x9a4c, 0x9afc, 0xba68, 0xc084, ...]
>       69           xpacd [0x4580, 0x6250, 0x6250, 0xe8bc, 0xf380, 0x10ee0, 0x10fd0, 0x11008, ...]
>       67          paciza [0x280c, 0x560c, 0x6ae8, 0x6b00, 0x6b10, 0x6b20, 0x6b30, 0x6b40, ...]
>       65          autdza [0x457c, 0x624c, 0x624c, 0xe8b8, 0xf37c, 0x10edc, 0x10fcc, 0x11004, ...]
>       21           xpaci [0xd948, 0xe500, 0xf068, 0xf324, 0xf584, 0x1a204, 0x1a3e0, 0x1a9c0, ...]
>       16          pacdza [0x8c30, 0xc7a0, 0x109e0, 0x10ae8, 0x15db4, 0x1be2c, 0x1c0ec, 0x1c504, ...]
>       13           pacib [0x19b48, 0x28950, 0x57a20, 0x57bf8, 0x57be4, 0x57bb0, 0x57d48, 0x57dc8, ...]
>       11           autib [0x57a0c, 0x57b9c, 0x57d34, 0x57db4, 0x57f38, 0x57fdc, 0x58124, 0x58240, ...]
>        2           pacdb [0x19b58, 0x28948]
>        2           autdb [0x52fd8, 0x53538]
>        1           autia [0x585b0]
>

**Comment by lwerdna** [comment]
These instructions won't assemble in keystone or execute in unicorn, so I'm doing my best to imagine how they'd behave given the docs. So mistakes are likely and another set of eyes would be appreciated.

See the commented tests atop arm64test.py and uncomment and edit them as you lift.
