### ISSUE TITLE
Lifting intrinsics

### ISSUE THREAD

**Issue by yrp604** [Vector35/arch-arm64#3]
Hello,

I have a [plugin](https://github.com/yrp604/arm64_intrinsics) that lifts some instructions as intrinsics.

This plugin lifts two classes of instructions:
- Interrupt barriers are lifted as an intrinsic taking no args
- mrs/msr are implemented by adding a system register for each known MSR, then reading/writing to them as an intrinsic.

Is the lifting strategy you'd prefer for these instructions? Im very happy to roll the lifting of these instructions into mainline and kill that plugin if that's an option.

**Comment by lwerdna** [comment]
I think having them as part of the architecture, no longer requiring a plugin, is the simpler and better choice.  But I'd like to hear other opinions.

**Comment by yrp604** [comment]
Most of these are done now, so I think the issue can be closed ;)
