### ISSUE TITLE
Lifting svc, hvc, smc

### ISSUE THREAD

**Issue by yrp604** [Vector35/arch-arm64#33]
After discussing this a bit with Ryan, I have a proposal for how the svc, hvc, and smc instructions should be lifted. I'm creating this as an issue because this would affect all platforms and seems like a good type of thing to get feedback on.

Background info: svc is the equivalent instruction to syscall on x64 while hvc would be vmcall. smc would be like smmcall if such an instruction existed. Currently, svc is lifted as LLIL_SYSCALL and hvc and smc are unlifted.

Problem: from EL1, under common configs you can both hvc and smc. How should these be lifted in such a way that they're distinguishable? As an added benefit, similar to syscalls smc calls at least can have a calling convention (e.g. smccc) that would be nice to annotate.

There are two high level solutions I see: lift this as Trap or Syscall. While I'm not sure this is correct, I differentiate between these LLIL insrtuctions based on their returnability: something like eret would be a trap while an smc call would return to the subsequent instruction and thus be a syscall. Coupled with the ability to associate a calling convention with a syscall, lifting all of these instructions as syscall seems the most reasonable thing to me.

This however returns us to our original problem: how could we differentiate between hvc and and smc calls if they're both lifted as Syscall? My proposed solution here is to repurpose the fake reg syscall immediate we use to pass the svc immediate on platforms where its relevant. We would lift all three instructions as:
```
FAKEREG_SYSCALL_INFO  = (destination_exception_level << 16) | operand[0]
SYSCALL
```

So for example, `svc #0` would lift as `SYSCALL_INFO = 1 << 16 | 0 ; SYSCALL`, `svc #41` would be  `SYSCALL_INFO = 1 << 16 | 0x41 ; SYSCALL`, and `smc #41` would be  `SYSCALL_INFO = 3 << 16 | 0x41 ; SYSCALL`. Each platform would then use this info to determine how to resolve the calls type info. E.g. arm64 linux would look at the destination exception level, and if it's one, apply the syscall types. If it's two or three, look for relevant hypervisor/trustzone calling conventions to apply.

The lifting/architecture side of these changes are pretty easy and is largely done on a branch [here](https://github.com/yrp604/arch-arm64/commit/f59a0fd5d6de1f058d6b390cc836476480757693). I don't really have an idea of the scope of the platform or other changes that'd be required here, or if there are other caveats that would make this a bad idea.

Happy to take any feedback or alternative suggestions, cheres.

**Comment by lwerdna** [comment]
All three would lift to LLIL_SYSCALL, but we'd override bits b10, b9, b8 as flags to mark which of the three source instructions the lift was from, right?

If so, it sounds fine to me. I'm awaiting Ryan's nod and I'll implement it, using the branch you provided. Or merge a PR if you make it.

**Comment by yrp604** [comment]
Close -- all three would lift to LLIL_SYSCALL but bits 16 and 17 would be used to encode the _destination_ exception level. The bottom 16 bits are used to store the syscall immediate from the instruction.

For svc the top 16bits will always be 1, for hvc they will always be 2, and for smc they will always be 3. Then, when resolving the type info for the call these bit would be used as a data source. E.g. if they're a 1, it's a syscall and if they're a 3 it's smccc.

**Comment by rssor** [comment]
I think it would be better to to count from 0, that way the the ids for currently shipping syscalls remain the same. `hvc` and `smc` are in the minority and also not currently supported, so partitioning the syscall id space such that everything currently in use stays the same and the newly supported calls get unused ranges seems easiest.

I’d also be tempted to use bits 30 and 31 for this purpose but that’s potentially cramped if we need to expand in the future. It’s probably worth making syscall ids 64-bit in the core if we need to expand anyways. That said, since these are encoded as 16-bit immediates there’s no reason using bits 16 and 17 as proposed wouldn’t probably be fine.

**Comment by lwerdna** [comment]
Went with b31,b30 and EL numbers, so {1,2,3} for {svc,hvc,smc}. Easily changeable. Now I need to check the platform code to make sure it handles these new bits.
