### ISSUE TITLE
Aarch64 Table C3-37 Arithmetic (extended register) instructions are improperly lifted

### ISSUE THREAD

**Issue by plafosse** [Vector35/arch-arm64#4]
Add/sub by extended register is being improperly lifted. Currently the extend is being applied to the 3rd parameter instead of the 2nd as its supposed to be.

**Comment by lwerdna** [comment]
> Currently the extend is being applied to the 3rd parameter instead of the 2nd as its supposed to be.

@plafosse I think it might supposed to be applied to the 3rd parameter. Could you check me before I close this?

In `ADD <Rd>, <Rn>, <Rm>, {, <extend>}` I'm calling the Rd/Rn/Rm the 1st/2nd/3rd params . The operation is `<Rd> = <Rn> + ExtendReg(<Rm>)`. Operational pseudocode available at http://shell-storm.org/armv8-a/ISA_v85A_A64_xml_00bet8_OPT/xhtml/add_addsub_ext.html confirms this.

**Comment by lwerdna** [comment]
The referencing commit in this thread includes the tests that show the issue fixed. Here's a direct link for quick reference: https://github.com/Vector35/arch-arm64/blob/master/arm64test.py
