### ISSUE TITLE
Lift REV instructions

### ISSUE THREAD

**Issue by brinlyau** [Vector35/arch-arm64#54]
for reversing bytes (examples are from the dyld binary):

```
 unlifted instructions in bndb
       17           rev64 [0x189a0, 0x59a60, 0x59a64, 0x59a68, 0x59a6c, 0x59a70, 0x59a74, 0x59a78, ...]
       16           rev32 [0x590a8, 0x590b0, 0x590b8, 0x590c0, 0x5918c, 0x591b4, 0x591cc, 0x591e0, ...]
 
```

Probably should do REV16 too.

**Comment by yrp604** [comment]
These can pretty trivially be lifted as intrinsics, see b94808fe6dff516a5f043e1cfd9f79db78e254df. The only reason I didnt do this before was I wasnt exactly sure how rev{16,32,64} was different from rev.

**Comment by brinlyau** [comment]
Ah, I didn't see that rev was done.
