### ISSUE TITLE
Fails to disassemble `hint #127`

### ISSUE THREAD

**Issue by blacktop** [Vector35/arch-arm64#78]
`error = failed to decompose instruction 0xd5032fff: DECODE_STATUS_UNMATCHED`

Maybe this isn't in the spec? It is however, in the llvm tests.

```bash
❯ echo "0xff, 0x2f, 0x03, 0xd5" | llvm-mc -disassemble -arch=arm64 -mattr=v8.5a 

        .section        __TEXT,__text,regular,pure_instructions
        hint    #127
```

**Comment by lwerdna** [comment]
Indeed, capstone, libopcodes, and llvm all agree it should be `hint #0x7f`:

```
                                FF 2F 03 D5                             D5 03 2F FF
                                -----------                             -----------
binja_aarch64.so                0: ERROR: -1                               0: ERROR: -1
capstone_aarch64.so             0: hint #0x7f                              0: ERROR: -1
libopcodes_aarch64.so           0: hint #0x7f                              0: .inst 0xff2f03d5 ; undefined
libopcodes_aarch64_ilp32.so     0: hint #0x7f                              0: .inst 0xff2f03d5 ; undefined
llvm_aarch64.so                 0: hint #0x7f                              0: ERROR: -1
llvm_aarch64_1a.so              0: hint #0x7f                              0: ERROR: -1
llvm_aarch64_2a.so              0: hint #0x7f                              0: ERROR: -1
llvm_aarch64_3a.so              0: hint #0x7f                              0: ERROR: -1
llvm_aarch64_4a.so              0: hint #0x7f                              0: ERROR: -1
llvm_aarch64_5a.so              0: hint #0x7f                              0: ERROR: -1
llvm_aarch64_all.so             0: hint #0x7f                              0: ERROR: -1
```

In the spec's encoding index for Hints: http://tmp2.dreamhosters.com/ISA_A64_xml_v9A-2021-03/encodingindex.html#hints the table is indexed by CRm and op2. CRm in your example is 0b1111 so it doesn't have an entry in table. Except HINT appears in the first entry with no CRm and no op2 specified, and I think ARM meant that HINT should be the fallback if none of the other constraints on CRm and op2 match.

But if you descend a step further into Hints: http://tmp2.dreamhosters.com/ISA_A64_xml_v9A-2021-03/hint.html you find the preceeding table was a pre check for this switch statement. CRm:op2 is 0b1111111 and there is no case for that. It's supposed to execute the EndOfInstruction() pcode and do nothing. Ok, so it _does_ nothing, but how should it be presented? As a NOP? As a HINT? I think ARM might be improperly mixing semantics into the decoding (syntactic) logic with the invocation of EndOfInstruction().

Under assembler symbols it says:

> For allocated encodings of "CRm:op2": A disassembler will disassemble the allocated instruction, rather than the HINT instruction.

I'm afraid of committing [inverse error](https://en.wikipedia.org/wiki/Denying_the_antecedent) here, but I think ARM intends for us to infer:

> For **unallocated** encodings of "CRm:op2": A disassembler will disassemble the HINT instruction rather than the allocated instructions.

**Comment by lwerdna** [comment]
Thank you for filing this issue 👍

**Comment by blacktop** [comment]
Wow thanks for the incredibly fast turn-around!
