### ISSUE TITLE
ARM64 conditional compare (`CCMP`) instruction is not properly lifted

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/arch-arm64#84]
If I understand correctly, this code checks the value of `w1` against a handful of constants — effectively a big `if (w1 == X || w1 == Y || ...)` — but when lifted the actual constants are not visible, which seems like bad lifting / incorrect behavior.

See the following comparison between the disassembly and MLIL:

<img width="1120" alt="mlil" src="https://user-images.githubusercontent.com/41548458/135922907-5dd2693d-3fd3-447b-b5c3-f5712093118d.png">

The pictured BNDB:
[arm64_ccmp_lifting.bndb.zip](https://github.com/Vector35/binaryninja-api/files/7281259/arm64_ccmp_lifting.bndb.zip)

**Comment by lwerdna** [comment]
At first I was sure determination of whether flags are set should remain in lifter, as the pcode for ccmp is very clearly missing its usual `boolean setflags = (S == '1')` or any mention of setflags at all:

```
integer n = UInt(Rn);
integer datasize = if sf == '1' then 64 else 32;
boolean sub_op = (op == '1');
bits(4) condition = cond;
bits(4) flags = nzcv;
bits(datasize) imm = ZeroExtend(imm5, datasize);
```

But as you point out, it sets the flags in **both** cases, so no determination is unnecessary. If I had a contact at ARM I'd send them a likely bug report.

So I'll override the pcode and set setflags in the decoding context :/.

Applies to at least these encodings:

```
CCMP_imm
CCMP_reg
FCCMPE_float
FCCMP_float
CCMN_imm
CCMN_reg
```

**Comment by lwerdna** [comment]
Woops, those are what the spec calls "instruction forms". The affected encodings are:

```
CCMP_32_condcmp_imm
CCMP_64_condcmp_imm
CCMP_32_condcmp_reg
CCMP_64_condcmp_reg
FCCMPE_H_floatccmp
FCCMPE_S_floatccmp
FCCMPE_D_floatccmp
FCCMP_H_floatccmp
FCCMP_S_floatccmp
FCCMP_D_floatccmp
CCMN_32_condcmp_imm
CCMN_64_condcmp_imm
CCMN_32_condcmp_reg
CCMN_64_condcmp_reg
```

**Comment by lwerdna** [comment]
Thanks for the detailed report and [test](https://github.com/Vector35/arch-arm64/pull/83/commits/887d5ee705eb40b9977a58ef3cb3c2a5f070fc77)!
