### ISSUE TITLE
Possibly incorrect operand class for some system registers operations

### ISSUE THREAD

**Issue by yrp604** [Vector35/arch-arm64#87]
forked from https://github.com/yrp604/bad64/pull/9

My understanding of the disassembler is that if the operand class it spits out is REG_SYSREG, then the operand's sysreg field should be a sysreg defined in the arch. However, disassembling `d53fe297` gives me an operand with REG_SYSREG as the class but no known system register. In this case, I would expect the operand class to be IMPLEMENTATION_SPECIFIC, with populated values in `implspec[]` to resolve it.

Is this a disassembler bug or is my understanding incorrect?

**Comment by lwerdna** [comment]
I don't disagree, and can't explain why I once thought having an enum value SYSREG_UNKNOWN and returning "unknown_catchall" from get_system_register_name() for it was correct. Handling of `ENC_MRS_RS_SYSTEMMOVE` and `ENC_MSR_SR_SYSTEMMOVE` relies on the macro `ADD_OPERAND_SYSTEMREG_SENSE` which relies on `get_system_register_name()` returning an empty string to conclude it's implementation specific.

before:
```
$ ./test d53fe297
aarch64_decompose() returned 0
  instr.insword: D53FE297
 instr.encoding: 1099 MRS_RS_systemmove
instr.operation: 579 mrs
 instr.setflags: 0
instr.operands[0]
	.class: REG
	.arrSpec: 0 NONE
instr.operands[1]
	.class: SYS_REG
	.arrSpec: 0 NONE
aarch64_disassemble() returned 0
D53FE297: mrs	x23, unknown_catchall
```

after:
```
$ ./test d53fe297
aarch64_decompose() returned 0
  instr.insword: D53FE297
 instr.encoding: 1099 MRS_RS_systemmove
instr.operation: 579 mrs
 instr.setflags: 0
instr.operands[0]
	.class: REG
	.arrSpec: 0 NONE
instr.operands[1]
	.class: IMPLEMENTATION_SPECIFIC
	.arrSpec: 0 NONE
aarch64_disassemble() returned 0
D53FE297: mrs	x23, s3_7_c14_c2_4
```

**Comment by lwerdna** [comment]
Thank you for the report!

**Comment by lwerdna** [comment]
Doh, tested disassembler but not the arch, SYSREG_UNKNOWN is needed, one sec...

**Comment by lwerdna** [comment]
> I don't disagree, and can't explain why I once thought having an enum value SYSREG_UNKNOWN and returning "unknown_catchall" from get_system_register_name() for it was correct.

A textbook of example of [Chesterson's Fence](https://fs.blog/chestertons-fence/).

That enum was needed as either an input or output when lifting to ARM64_INTRIN_MRS or ARM64_INTRIN_MRS when the instruction doesn't name one of the system registers named to the architecture.
